/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/components/**/*.{html,tsx,ts}",
    "./src/pages/**/*.{html,tsx,ts}",
    "./src/*.{html,tsx,ts}"
  ],
  theme: {
    extend: {//All this it to get markdown styled better
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'inherit',
            '--tw-prose-headings': 'inherit',
            '--tw-prose-links': 'inherit',
            '--tw-prose-bold': 'inherit',
            '--tw-prose-code': 'inherit',
            '--tw-prose-bullets': 'inherit',
            '--tw-prose-counters': 'inherit',
            '--tw-prose-lead': 'inherit',
            '--tw-prose-quotes': 'inherit',
            '--tw-prose-quote-borders': 'inherit',
            '--tw-prose-captions': 'inherit',
            '--tw-prose-hr': 'inherit',
            '--tw-prose-pre-code': 'inherit',
            '--tw-prose-pre-bg': 'inherit',
            '--tw-prose-th-borders': 'inherit',
            '--tw-prose-td-borders': 'inherit',
            '--tw-prose-th-bg': 'inherit',
            '--tw-prose-td-bg': 'inherit',
            '--tw-prose-invert-body': 'inherit',
            '--tw-prose-invert-headings': 'inherit',
            '--tw-prose-invert-links': 'inherit',
            '--tw-prose-invert-bold': 'inherit',
            '--tw-prose-invert-code': 'inherit',
            '--tw-prose-invert-bullets': 'inherit',
            '--tw-prose-invert-counters': 'inherit',
            '--tw-prose-invert-lead': 'inherit',
            '--tw-prose-invert-quotes': 'inherit',
            '--tw-prose-invert-quote-borders': 'inherit',
            '--tw-prose-invert-captions': 'inherit',
            '--tw-prose-invert-hr': 'inherit',
            '--tw-prose-invert-pre-code': 'inherit',
            '--tw-prose-invert-pre-bg': 'inherit',
            '--tw-prose-invert-th-borders': 'inherit',
            '--tw-prose-invert-td-borders': 'inherit',
            '--tw-prose-invert-th-bg': 'inherit',
            '--tw-prose-invert-td-bg': 'inherit',
            color: 'inherit',
            fontFamily: 'inherit',
            fontSize: 'inherit',
            lineHeight: 'inherit',
            'h1, h2, h3, h4, h5, h6': { color: 'inherit' },
            'strong': { color: 'inherit' },
            'a': { color: 'inherit' },
            'em': { color: 'inherit' },
            'blockquote': { color: 'inherit !important', borderColor: 'inherit !important' },
            'ul > li::marker': { color: 'inherit !important' },
            'ol > li::marker': { color: 'inherit !important' },
            'hr': { borderColor: 'inherit !important' },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
            'thead th': { color: 'inherit', backgroundColor: 'inherit' },
            'th': { color: 'inherit', backgroundColor: 'inherit' },
            'td': { color: 'inherit', backgroundColor: 'inherit' },
          },
        },
      },
    },
  },
  daisyui: {
    themes: [
      {
        dark: {
          "primary": "#0ea5e9",
          "secondary": "#38bdf8",
          "accent": "#7dd3fc",
          "neutral": "#6b7280",
          "base-100": "#111827",
          "base-200": "#1f2937",
          "base-300": "#374151",
          "info": "#38bdf8",
          "success": "#bef264",
          "warning": "#fb923c",
          "error": "#ef4444",
        },
        light: {
          "primary": "#0ea5e9",
          "secondary": "#38bdf8",
          "accent": "#7dd3fc",
          "neutral": "#6b7280",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "info": "#38bdf8",
          "success": "#22c55e",
          "warning": "#fb923c",
          "error": "#ef4444",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    themeRoot: ":root",
  },
  plugins: [
    require('daisyui'),
    require('@tailwindcss/typography'),
  ],
}

